### ISSUE TITLE
Publicação no HL7 Registry

### ISSUE THREAD

**Issue by kyriosdata** [kyriosdata/ig#3]
O Guia está publicado em https://fhir.org/guides/registry/. Contudo, ainda não é encontrado em https://registry.fhir.org/, apesar do pull request ter sido aprovado, conforme https://github.com/FHIR/ig-registry/pull/213. Considere que a URL canônica foi alterada. Agora usamos https://fhir.fabrica.inf.ufg.br/ig.

Passos para registro estão documentados em https://registry.fhir.org/submit. O arquivo package-feed está com endereços equivocados? Um novo pull request atualizando deve ser realizado. O package-feed supostamente também deve estar disponível em https://fhir.fabrica.inf.ufg.br/ig?

Uma fonte que pode ser útil é https://github.com/commonprofiles-care/fhir pois já está funcionando. Adicionalmente, os links abaixo fornecem informações adicionais:

- https://build.fhir.org/ig/commonprofiles-care/fhir/
- https://github.com/FHIR/auto-ig-builder/blob/master/README.md (auto-builder)
- https://fhir.github.io/auto-ig-builder/builds.html (onde seria disponibilizado)

**Comment by muriloluz** [comment]
Ok
